services:
  frontend:
    build: ./FE/GenCare
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_API_URL=http://backend:7722/api
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./APIGeneCare
    ports:
      - "7722:7722"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=sqlserver;database=GeneCare;User Id=sa;Password=ABC@abc123;TrustServerCertificate=True
    depends_on:
      - sqlserver
    restart: unless-stopped

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "ABC@abc123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: unless-stopped
