name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file APIGeneCare/Dockerfile --tag my-image-name:$(date +%s)

      - name: Start SQL Server using GitHub Action
        uses: sharathck087/sqlserver-github-action@v1
        with:
          sa-password: 12345
          show-log: false
