name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Database Docker image
        working-directory: ./DataBase
        run: docker build . --file Dockerfile --tag genecare-database:latest

      - name: Build Backend Docker image
        working-directory: ./APIGeneCare
        run: docker build . --file Dockerfile --tag genecare-backend:latest

      - name: Build Frontend Docker image
        working-directory: ./FE/GenCare
        run: docker build . --file Dockerfile --tag genecare-frontend:latest
